### ISSUE TITLE
Give new headers to the website

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#104]
Currently the header looks like this. ⬇️ 

<img width="256" alt="Screenshot 2022-10-02 at 1 12 17 AM" src="https://user-images.githubusercontent.com/91758830/193425805-5c8d734c-4b2a-4803-b9d7-07ff6eac7131.png">

But we need to update the Vercel logo to ClueLess logo and the `ClueLess` name to `ClueLess - First Contribution`.

Here is a link to the ClueLess official logo. [ClueLess Logo](https://www.clueless.tech/ClueLess%20Logo.png).

Here is documentation on how to do it. [Next.js Head tag Doc](https://nextjs.org/docs/api-reference/next/head)

**Comment by dishant-yadav** [comment]
@Rajdip019 I would like to work on this issue. Can you please assign me this issue?

**Comment by Rajdip019** [comment]
Sure go ahead. @dishant-yadav

**Comment by dishant-yadav** [comment]
Thanks @Rajdip019 for assigning me this issue

**Comment by dishant-yadav** [comment]
Should I be using .ico file for favicon? @Rajdip019

**Comment by dishant-yadav** [comment]
@Rajdip019 
I have raised the pr please review it and let me know if there are any changes to be made.
[PR Link](https://github.com/Clueless-Community/first-contribution/pull/105)

**Comment by Rajdip019** [comment]
Closing this as it is done.
