### ISSUE TITLE
Fix: Website link needs to be updated

### ISSUE THREAD

**Issue by VividhPandey003** [Clueless-Community/first-contribution#107]
The Website link shared in the Readme File on clicking redirects to a github pages link.
<img width="645" alt="image" src="https://user-images.githubusercontent.com/91251535/193430664-38913c5c-5a8e-4285-a957-f45b47b69748.png">

However, since the website is deployed in vercel with the link [CluelessVercel]([clueless.vercel.app/](https://clueless.vercel.app/)) the readme file needs to be updated.

**Comment by VividhPandey003** [comment]
On checking the Readme File I discovered that no link is provided in the Readme File. 
<img width="412" alt="image" src="https://user-images.githubusercontent.com/91251535/193430685-b2fe153f-bae4-42a4-a740-f7b32148fae3.png">

Although this is a small Readme Fix, I would love to work on it.

**Comment by Rajdip019** [comment]
Sure, @VividhPandey003 go ahead. Assigning you this issue.

**Comment by Rajdip019** [comment]
Closing this as this is done.

**Comment by VividhPandey003** [comment]
Hey @Rajdip019 I don't know how. I guess there has been a recent push but the issue is already fixed.😂
<img width="524" alt="image" src="https://user-images.githubusercontent.com/91251535/193444693-02e53b57-cc93-4678-b9f4-3ad5a3d409e4.png">

So I guess you should close this issue.
