### ISSUE TITLE
Make Contributions.md!!

### ISSUE THREAD

**Issue by AKACHI-4** [Clueless-Community/first-contribution#111]
Hey, I would like to recommend adding contributors.md file so the name of contributors will be visible on the main repo.

### Screenshots

![pr4](https://user-images.githubusercontent.com/99159580/193439266-0868f6a6-21e8-48bc-81e0-97d3de6ce876.PNG)

**Comment by Abdirizaks12** [comment]
assign me please

**Comment by AKACHI-4** [comment]
I am already working on it and soon I will generate PR for same

**Comment by Rajdip019** [comment]
Hey @AKACHI-4. This is really good idea can you do the same with the profile pictures that will be amazing.

**Comment by AKACHI-4** [comment]
Okay @Rajdip019 why not

**Comment by Rajdip019** [comment]
Closing this as it is already solved.
