### ISSUE TITLE
Linkedin link is not present for Nikhil

### ISSUE THREAD

**Issue by tushar54594** [Clueless-Community/first-contribution#120]
In the our team section of the website, the Linkedin link is not present for @nikhil25803. 

Screenshot:
![Screenshot (590)](https://user-images.githubusercontent.com/94536522/193442503-30d5fc17-2ca5-4f4a-9c14-2a29a6c0a695.png)

**Comment by Rajdip019** [comment]
Hey, nice point.

What you can do is change his profile details. 

Change the image to this.
![bc40fafa-37c2-46e1-9c38-8e4c036966d0](https://user-images.githubusercontent.com/91758830/193443649-6307cf46-eb66-4db7-a704-032ce9bb6804.jpg)

Description to this : Into Machine Learning | Backend Development | Python | Django | Open Source🚀 |
And LinkedIn Profile URL add that this : https://www.linkedin.com/in/nikhil-raj-117246232/

@tushar54594

**Comment by tushar54594** [comment]
Closing this issue as this is completed
