### ISSUE TITLE
Repeated Data

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#123]
Some of the contributor data is repeated ( 2- 4 times) due to some bad PR merge.

Here is picture of that. ⬇️ 
<img width="1266" alt="Screenshot 2022-10-02 at 1 31 14 PM" src="https://user-images.githubusercontent.com/91758830/193444352-0c943166-1488-4ea9-a67a-fd0c45155dbc.png">

One need to change the `data/contributors.js` file and remove all the duplicate contributor data. But be very careful not to remove any authentic contributor data.

**Comment by Yash-Parwani** [comment]
hey @Rajdip019 can i look into this?

**Comment by Ahnaf-codes** [comment]
can i work on this

**Comment by Rajdip019** [comment]
Hey, @Yash-Parwani go ahead. And sorry @Ahnaf-codes we have first come first serve policy. Please see other issues.

**Comment by Yash-Parwani** [comment]
ok thanks @Rajdip019

**Comment by Rajdip019** [comment]
This issue is solved thanks to @Yash-Parwani , so closing this issue.
