### ISSUE TITLE
Video Issue in darkmode

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#124]
In the dark mode there is an issue in the darkmode.

Here is a reference to that. ⬇️ 

<img width="1082" alt="Screenshot 2022-10-02 at 1 40 39 PM" src="https://user-images.githubusercontent.com/91758830/193444597-c81a0f9f-6fa6-491b-815e-8e9eb8155c3c.png">

**Comment by Ahnaf-codes** [comment]
I can do this. assign me @Rajdip019

**Comment by Rajdip019** [comment]
Sure go ahead. @Ahnaf-codes
