### ISSUE TITLE
Spacing between the LinkedIn and the GitHub icons

### ISSUE THREAD

**Issue by prakhar-1005** [Clueless-Community/first-contribution#156]
In the Our team section of the website, the spacing between the LinkedIn and GitHub icon is not proper for @nikhil25803.

Screenshot:
![Screenshot (1)_LI](https://user-images.githubusercontent.com/94559623/193468858-00d2bdb8-ee53-4d70-a18f-1523340382a9.jpg)

**Comment by aniket2003** [comment]
@prakhar-1005 can you please assign me with this issue , I would like to solve it .

**Comment by harsitagarwalla187** [comment]
Can you assign it to me?

**Comment by Rajdip019** [comment]
Ge ahead and solve this @prakhar-1005 .

**Comment by codeswithroh** [comment]
@Rajdip019 This is already fixed. Kindly close this issue
