### ISSUE TITLE
Add Contributor's Profile Images !!

### ISSUE THREAD

**Issue by AKACHI-4** [Clueless-Community/first-contribution#164]
**Update** 
1. Contributor's profile image will appear at the bottom of README.md
2. CONTRIBUTING.MD will be modified to aware newcomers about contribution.

**Comment by Rajdip019** [comment]
Yes, let's work on this now! @AKACHI-4

**Comment by codeswithroh** [comment]
@AKACHI-4 Should the images be added on a new folder or should it be given from a link ?

**Comment by AKACHI-4** [comment]
It should be in the README.md

**Comment by AKACHI-4** [comment]
#167 PR generated and #164 issue solved as I am working on it under the last issue but it gets closed so I generated it here merge PR so changes will get visible for everyone 

Thanks, @Rajdip019

**Comment by Rajdip019** [comment]
Yup that's better. And more clear.

**Comment by AKACHI-4** [comment]
Yep 😄👍

**Comment by codeswithroh** [comment]
@AKACHI-4 I couldn't find the place to add the contributors image in the Readme.md file

**Comment by AKACHI-4** [comment]
Hey @codeswithroh actually I have already generated a PR regarding this .....checkout their you will get some idea about it.
