### ISSUE TITLE
Fix Dark Mode

### ISSUE THREAD

**Issue by akshay-Kalekar** [Clueless-Community/first-contribution#169]
Fixes required in dark mode
1) Add Dark Mode to Discord Component 
2) Change color of LinkedIn and Github Icon in profile section in dark mode to make in more visible

Issue
![image](https://user-images.githubusercontent.com/50509605/193473109-fa2d512f-5503-43df-884f-876fd9548941.png)

**Comment by yes-im-harsh** [comment]
Please assign it to me, I would love to work on this.

**Comment by mehraankush** [comment]
do i have to make the background dark or   a kind of button that switches between dark and light modes

**Comment by yes-im-harsh** [comment]
@akshay-Kalekar Check PR, Fixed Dark Mode #171

**Comment by SahilSingh177** [comment]
Please assign this to me.

**Comment by akshay-Kalekar** [comment]
@yes-im-harsh @SahilSingh177 @mehraankush  ,I can't assign this issue to anyone.as I am also one of the contributor .
I created this issue as, if the author feel like this change is required in dark mode and if approved can assign it to me.

**Comment by yes-im-harsh** [comment]
@Rajdip019 I think this has been resolved. PR merged #171 
Now we can close this issue
