### ISSUE TITLE
New page on GitHub basic commands.

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#209]
One should make the page for github basic commands for both dark and light mode.

The page route will be `whattodo/basic-github-commands`.

And the data it will contain is [this](https://github.com/Clueless-Community/first-contribution/blob/main/KnowGitMore.md).

You need to built it using tailwind CSS and maintain the existing design system.

**Comment by pratham4434** [comment]
I'll do it, assign it to me!

**Comment by Rajdip019** [comment]
Sure @pratham4434

**Comment by Siddharth9890** [comment]
I can help you for this

**Comment by Rajdip019** [comment]
Make the path form ../../components/gitCom to ../../components/GitCom .

The reason is not type sensitive about casing but while deployment it gets deploys in a linux machine which is type sensitive so it will not be able to find the file in the path and deployment will fail.

make these changes and make a new PR. @pratham4434

**Comment by Rajdip019** [comment]
This issue is done. So, closing this PR.
