### ISSUE TITLE
Make Dark mode default for the website.

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#211]
We need to make the dark mode default for the website. For now it's light mode that pops up in the first time or when reloaded.

Also when page refresh the mode should not switch. 

Here is the website link : [First Contribution Website](https://clueless.vercel.app/)

**Comment by Eyesnatcher-coder** [comment]
Hello @Rajdip019 I would like to work on the issue, could you please assign it to me ?

**Comment by Rajdip019** [comment]
Sure go ahead. @Eyesnatcher-coder

**Comment by Eyesnatcher-coder** [comment]
Completed the issue, made default theme as dark, loved contributing to you 💯 .

**Comment by Eyesnatcher-coder** [comment]
Hello @Rajdip019 , Just a gentle reminder that I have completed the task please, mark as hactoberfest-accepted, I would greatly appreciated for the same.
Thanks :)

**Comment by Rajdip019** [comment]
Your PR is not merged yet. Please view the comments in the PR. @Eyesnatcher-coder

**Comment by Rajdip019** [comment]
This issue is resolved I guess. So closing this issue
