### ISSUE TITLE
Add Main Website Link to Navbar

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#212]
After what to do you need to add `Visit main website` in the Navbar and it will be a `anchor` tag with a `target="_blank"`

<img width="1440" alt="Screenshot 2022-10-04 at 2 26 39 AM" src="https://user-images.githubusercontent.com/91758830/193681112-30d17767-f8c8-469e-9e51-2e2f8f8881bd.png">

And also remove the link to Home from Navbar.

**Comment by pratham4434** [comment]
assign this to me, I'll do it

**Comment by Rajdip019** [comment]
@pratham4434 make sure to add `https://www.clueless.tech/` link to the visit main website button. Now it's pointing to `clueless.vercel.app` website.

**Comment by devilkiller-ag** [comment]
Hi @Rajdip019 Can you assign this issue to me also?

**Comment by Rajdip019** [comment]
This issue is solved so closing this issue.
