### ISSUE TITLE
Change ClueLess Logo

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#213]
Now the looks like this. ⬇️ 
<img width="186" alt="Screenshot 2022-10-04 at 2 26 47 AM" src="https://user-images.githubusercontent.com/91758830/193681542-d74f732c-9120-48f3-829a-62a0e671ed7e.png">

But we need to change the terminal logo to the main logo of clueless.

Here is the LOGO we want.
![ClueLess Logo](https://user-images.githubusercontent.com/91758830/193681715-ffbcce96-af38-4f55-9f4e-8a791ad56467.png)

But you need to remove the background of the image first or make the image corners rounded to make it look better.

**Comment by STM3900** [comment]
Hello, i can work on this! Can you asign me ?

**Comment by Rajdip019** [comment]
Go ahead! @STM3900

**Comment by STM3900** [comment]
Thanks! Just to be sure, you want me to replace the logo from the navbar to this one?

**Comment by Rajdip019** [comment]
From footer also. @STM3900
