### ISSUE TITLE
Need a banner to the GitHub basic commands page.

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#219]
We need a banner like this for both dark mode and light mode. You can re-use the code of this banner as well.

<img width="1261" alt="Screenshot 2022-10-04 at 10 08 24 AM" src="https://user-images.githubusercontent.com/91758830/193735639-3f0df37d-8007-44be-ba30-77d306904e03.png">

The button should point to `/whattodo/basic-github-commands` and it should be a `<Link>` tag.

The text on the left will be `Learn basic GitHub commands`.

**Comment by Siddharth9890** [comment]
I can take this task

**Comment by Siddharth9890** [comment]
Where should i place this banner below the existing one or in a new page?

**Comment by Rajdip019** [comment]
Place it above the video section at the bottom in the what to do page. @Siddharth9890

**Comment by Siddharth9890** [comment]
![image](https://user-images.githubusercontent.com/63333707/193993768-30d35594-4548-49fa-9e1e-1f8d0ea903c6.png)
This will be fine i guess?

**Comment by Rajdip019** [comment]
If you are done with the banner can you please link the PR here? @Siddharth9890

**Comment by Siddharth9890** [comment]
Done

**Comment by Rajdip019** [comment]
This issue is solved so closing this PR.
