### ISSUE TITLE
Ridham Singhal- added transitional underline to items in nav and footer 

### ISSUE THREAD

**Issue by RidhamRj** [Clueless-Community/first-contribution#223]
### This is Ridham Singhal. And I will be adding my data to do my first contribution as well as get a card on the website.
preview-

(https://user-images.githubusercontent.com/86556438/193767592-0519028b-99e0-4bc8-ad1c-0b76e8d2b11a.webm)

**Comment by RidhamRj** [comment]
@Rajdip019 pls look to this

**Comment by RidhamRj** [comment]
also i am a high schooler so how do i fill contributor.js

**Comment by pandeyom331** [comment]
resolving the issues

**Comment by RidhamRj** [comment]
@pandeyom331 any updates related to this?
 

> also i am a high schooler so how do i fill contributor.js

**Comment by RidhamRj** [comment]
kindly assign as well

**Comment by Rajdip019** [comment]
This looks cool work on this ! @RidhamRj

**Comment by RidhamRj** [comment]
> also i am a high schooler so how do i fill contributor.js

wht abt this @Rajdip019
