### ISSUE TITLE
frequently asked question section on homepage

### ISSUE THREAD

**Issue by RidhamRj** [Clueless-Community/first-contribution#237]
### This is Ridham Singhal. And I will be adding my data to do my first contribution as well as get a card on the website.

like to add faq section to homepage

**Comment by Rajdip019** [comment]
Do we really need this? @Debajyoti14 , @nikhil25803 , @Roshaen ?

**Comment by Debajyoti14** [comment]
@RidhamRj Suggest some of the questions you think will be useful to visitors

**Comment by RidhamRj** [comment]
> Do we really need this? @Debajyoti14 , @nikhil25803 , @Roshaen ?

Tht is why I am thinking on the second thought
Like what questions can I add

**Comment by RidhamRj** [comment]
@Rajdip019 @Debajyoti14 let me know the questions to be added

**Comment by Rajdip019** [comment]
Yes let us discuss about it a bit. @RidhamRj

**Comment by Rajdip019** [comment]
We are not thinking about a FAQ page so closing this issue for now.

**Comment by Rajdip019** [comment]
We are not thinking about a FAQ page so closing this issue for now.

**Comment by Rajdip019** [comment]
We are not thinking about a FAQ page so closing this issue for now.

**Comment by RidhamRj** [comment]
Ohhk
