### ISSUE TITLE
Change the title of the GitHub Commands page

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#240]
Now the page title looks like this.

<img width="207" alt="Screenshot 2022-10-05 at 12 58 45 AM" src="https://user-images.githubusercontent.com/91758830/193908679-18aadbd4-e59b-44f1-9a0d-006abe1c2a45.png">

We need to change it to `GitHub commands` .

**Comment by saimaheshtaduri** [comment]
I can contribute @Rajdip019

**Comment by Rajdip019** [comment]
You are already to assigned to one!

**Comment by saimaheshtaduri** [comment]
@Rajdip019 I raised a PR to it. please review it #241

**Comment by Rajdip019** [comment]
Yup that is merged now. You can work on this! @saimaheshtaduri

**Comment by saimaheshtaduri** [comment]
U meant the title of the page right ? or the url ? @Rajdip019

**Comment by Rajdip019** [comment]
The title on the tab section of the browser. @saimaheshtaduri

**Comment by saimaheshtaduri** [comment]
ok, done raised the pr #242
