### ISSUE TITLE
Adding a search bar in all contributors page

### ISSUE THREAD

**Issue by saimaheshtaduri** [Clueless-Community/first-contribution#243]
Every newbie open source contributor, wants to see their name as a contributor. As there are many contributors right now, finding their name in that list is difficult. Thus a search bar might be a good use.

**Comment by Rajdip019** [comment]
Can you elaborate a bit how you are thinking to implement the search bar? @saimaheshtaduri

**Comment by saimaheshtaduri** [comment]
Like, to filter out the cards based on the search.

**Comment by Rajdip019** [comment]
Yeah I got that. I am talking about the implementation part. How you are planning to implement it? @saimaheshtaduri

**Comment by saimaheshtaduri** [comment]
I see at present, a `map` method is used, I will replace it with the `filter` method and display only those names that are the substrings of the searched text.

**Comment by Rajdip019** [comment]
Yup got it. You can work on this issue once you complete the FAB button where I have assigned you! 

Is that ok for you? @saimaheshtaduri

**Comment by saimaheshtaduri** [comment]
Can I instantly, change the link of the main website ? @Rajdip019

**Comment by Rajdip019** [comment]
Yes sure. @saimaheshtaduri

**Comment by Siddharth9890** [comment]
If no one is doing this one i can try using filter once #219 is done

**Comment by saimaheshtaduri** [comment]
I'm on it @Siddharth9890 😊

**Comment by Siddharth9890** [comment]
ok no problem @saimaheshtaduri

**Comment by Rajdip019** [comment]
Hey @saimaheshtaduri assigning you this issue as the previous issue is nicely done by you @saimaheshtaduri

**Comment by saimaheshtaduri** [comment]
Thanks @Rajdip019 😊

**Comment by Rajdip019** [comment]
This issue is solved so closing this Issue.
