### ISSUE TITLE
Change the Link to valid one.

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#244]
Currently the Visit Main website doesn't take user any where. 

<img width="1325" alt="Screenshot 2022-10-05 at 2 19 11 AM" src="https://user-images.githubusercontent.com/91758830/193925172-be351628-4409-4242-abd8-9703738e2b80.png">

We need to redirect users to the `https://www.clueless.tech/` website. 

So it will be an `anchor` tag with `target="_blank"` with it.

**Comment by saimaheshtaduri** [comment]
I can fix this. assign to me @Rajdip019

**Comment by Rajdip019** [comment]
You are already assigned to one issue. @saimaheshtaduri

**Comment by Pervolarakis** [comment]
can i work on this one?

**Comment by saimaheshtaduri** [comment]
As the issue is a small one, can I resolve this first and jump to FAB ? @Rajdip019

**Comment by Rajdip019** [comment]
No need of that @saimaheshtaduri . We want everyone to be able to contribute in a big or small issue.

**Comment by Rajdip019** [comment]
> can i work on this one?

Yes work on it. @Pervolarakis
