### ISSUE TITLE
Having a FAB in the website

### ISSUE THREAD

**Issue by saimaheshtaduri** [Clueless-Community/first-contribution#245]
In pages like contributors, which are so lengthy, it is better to have a Floating Action Button, on click takes user to the top of the page.

**Comment by Rajdip019** [comment]
Sure this will be a good thing to implement. First start work on this then we will be moving towards the search feature. @saimaheshtaduri

**Comment by saimaheshtaduri** [comment]
ok, thanks @Rajdip019

**Comment by devilkiller-ag** [comment]
Hey @Rajdip019 can you assign this work to me also?

**Comment by Rajdip019** [comment]
@saimaheshtaduri is working on this issue. @devilkiller-ag

**Comment by myGlitches** [comment]
Hey @saimaheshtaduri , is this issue fixed I can work on this with you if you want!
@Rajdip019 if possible let me know if I could help him with this issue
