### ISSUE TITLE
Scroll down button not visible.

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#254]
The scroll down button is not visible for both Dark mode and light mode. Here is a reference to that.

<img width="862" alt="Screenshot 2022-10-05 at 10 28 59 AM" src="https://user-images.githubusercontent.com/91758830/193984737-75b937bb-4835-4387-b01d-b47a31b38baa.png">

Also the gap between the main test and button section to the scroll down section should be less. So we need to also reduce  that and the jumping effect is too bouncy and distractive.We need to make it a lot smoother.

**Comment by SainathPoojary** [comment]
Hey @Rajdip019, I want to work on this. Please assign it to me.

**Comment by varunKT001** [comment]
@Rajdip019 Can I work on this?

**Comment by Rajdip019** [comment]
Sure. @SainathPoojary work on this. And sorry @varunKT001 . We have first come first serve policy.

**Comment by varunKT001** [comment]
@Rajdip019 No issues 😄

**Comment by SainathPoojary** [comment]
@varunKT001, Do we have to add a name into the contributors.js, After creating a branch or before? If before, then we have to commit the changes and then switch to a new branch. right?

**Comment by SainathPoojary** [comment]
@varunKT001 Got it 👍️

**Comment by Rajdip019** [comment]
Thanks @varunKT001 for your help.
