### ISSUE TITLE
Add a toggling navbar for smaller screens

### ISSUE THREAD

**Issue by codeswithroh** [Clueless-Community/first-contribution#258]
Currently the navbar remains open for smaller screens. Instead of that a toggling navbar would look good.
<img width="294" alt="nav" src="https://user-images.githubusercontent.com/77570394/193998034-c73012a1-177e-41c0-943c-bf8bc64a81d6.PNG">

**Comment by codeswithroh** [comment]
@Rajdip019 assign this to me

**Comment by Rajdip019** [comment]
Sure work on this issue. This will look cool. @codeswithroh

**Comment by Rajdip019** [comment]
I guess this issue is solved so closing this issue.

**Comment by codeswithroh** [comment]
Yup this is solved
