### ISSUE TITLE
Make the header sticky & Add a scroll to top button on right bottom side

### ISSUE THREAD

**Issue by SubxX** [Clueless-Community/first-contribution#260]
Hello guys this is my first issue on GitHub,  I would like to make the main header sticky for better access on scrollable pages & also add a scroll to the top button for better UX.

**Comment by Utkarsh212** [comment]
Please assign this to me, so that I can work on it

**Comment by SubxX** [comment]
I want to work on this @Utkarsh212

**Comment by Rajdip019** [comment]
Hey you can make the header sticky. The scroll to top button is in building process. @SubxX

**Comment by SubxX** [comment]
Got it

**Comment by aaushitiwari** [comment]
can you assign this to me?

**Comment by Rajdip019** [comment]
@SubxX is already working on this!
