### ISSUE TITLE
Fix Double Underline when hovering over Discord

### ISSUE THREAD

**Issue by devilkiller-ag** [Clueless-Community/first-contribution#271]
There is a double underline animation when hovering over the discord link in the footer while other links have only single underline animation. I want to fix this @Rajdip019 
![Screenshot (92)](https://user-images.githubusercontent.com/43639341/194028729-ec5868ae-63d2-4a16-b85f-a92da74e1173.png)

**Comment by devilkiller-ag** [comment]
![Screenshot (92)](https://user-images.githubusercontent.com/43639341/194028520-443ff0d3-ba49-4ba6-9b95-8eb69a845301.png)

**Comment by kala2** [comment]
Hi can i take this one? can you assign to me please?

**Comment by Rajdip019** [comment]
Hey @devilkiller-ag I have already assigned you an issue. So is there any problem I give this issue to @kala2 ?

**Comment by devilkiller-ag** [comment]
I can complete both if you don't mind.

**Comment by devilkiller-ag** [comment]
If @kala2 agrees we can work on it together.

**Comment by kala2** [comment]
Don't mind. I can take another ticket! it's all yours :)

**Comment by Rajdip019** [comment]
Okay, assigning it to @devilkiller-ag . You can find some issue in the website or make any enhancement feel free to raise an issue @kala2

**Comment by devilkiller-ag** [comment]
Thank You @Rajdip019

**Comment by devilkiller-ag** [comment]
Hey, @Rajdip019 I am wondering why this issue is open till now. Is there any problem with my PR?

**Comment by Rajdip019** [comment]
No this issue is solved so closing it. @devilkiller-ag
