### ISSUE TITLE
Fix Scroll Down FAB Button

### ISSUE THREAD

**Issue by devilkiller-ag** [Clueless-Community/first-contribution#272]
The floating scroll-down button is not working. Can I rectify it?
![Screenshot (93)](https://user-images.githubusercontent.com/43639341/194029400-9e23fa63-1361-40f9-801a-af965d7cddca.png)

**Comment by racky7** [comment]
@devilkiller-ag I want to work on this. Please assign it to me.

**Comment by devilkiller-ag** [comment]
@Rajdip019 is the maintainer. He has rights to assign issues. I am asking to work on this.

**Comment by Rajdip019** [comment]
Yes go ahead @devilkiller-ag
