### ISSUE TITLE
Change Color of "Contribute Now" Button on hover

### ISSUE THREAD

**Issue by devilkiller-ag** [Clueless-Community/first-contribution#296]
Every button on the site changes to blue when we hover over it but the "Contribute Now" button doesn't. It changes to grey in light mode but there is no change in dark mode. Can I rectify it? Please specify any other color if not blue to which it should change.

**Comment by vilasrhegde** [comment]
Hey @devilkiller-ag may I solve this one? I can make it very good looking

**Comment by burhanharoon** [comment]
Hy, can you assign this to me? I think the contribute now button's color should be the same as the other button's color on hover. It will ensure consistency in the website and make everything look polished and good. The tailwind `bg-blue-500` would be perfect for this!

**Comment by JatinSingh08** [comment]
Hey @devilkiller-ag, can please assign this issue to me ?

**Comment by Rajdip019** [comment]
Hey @devilkiller-ag work on this and make sure to change the same for every button like that. So it will be consistent and also add a `transition-all` class for a little transition effect.

**Comment by devilkiller-ag** [comment]
Thank you @Rajdip019

**Comment by Rajdip019** [comment]
This issue is solved so closing this issue. @devilkiller-ag
