### ISSUE TITLE
Add Socials to the footer

### ISSUE THREAD

**Issue by devilkiller-ag** [Clueless-Community/first-contribution#297]
The footer section of main [Clueless Site](https://www.clueless.tech/) and the [Clueless Community - First Contribution](https://clueless.vercel.app/) doesn't matches. 

Main Clueless Site Footer:
![Screenshot (99)](https://user-images.githubusercontent.com/43639341/194226662-3ede2e33-84fd-466b-aaf4-dd54eba5047a.png)
Clueless Community - First Contribution Footer:
![Screenshot (100)](https://user-images.githubusercontent.com/43639341/194226750-9643d0bf-3102-4513-aaf2-96c96cf4f8ab.png)

Can I rectify it?

**Comment by yash251** [comment]
Please assign this to me. Would love to work on this

**Comment by Rajdip019** [comment]
Both are different website so this should be different. @devilkiller-ag

**Comment by devilkiller-ag** [comment]
I was thinking about style and size.

**Comment by Rajdip019** [comment]
What you can do here is add LinkedIn, GitHub as well as twitter Link in the socials section of the footer. That would be useful. @devilkiller-ag

**Comment by Rajdip019** [comment]
Okay @devilkiller-ag

**Comment by devilkiller-ag** [comment]
Thank you @Rajdip019
