### ISSUE TITLE
Fixing the padding

### ISSUE THREAD

**Issue by myGlitches** [Clueless-Community/first-contribution#300]
### This is Suryadipta . And I have a suggestion on the [ClueLess - First Contribution Website](https://clueless.vercel.app/).

Can be viewed via this link-

https://prnt.sc/vl_OrN7HvLe8

Can I fix the padding and too much middle space area taken to a more balanced design?

Can you please assign this to me?

![Screenshot (338)](https://user-images.githubusercontent.com/65249625/194238571-7d664a79-a762-41af-8537-5e0ccc2a3d90.png)

**Comment by Rajdip019** [comment]
Go ahead @myGlitches . I have assigned you this!

**Comment by myGlitches** [comment]
Thanks! Working on it!

**Comment by Rajdip019** [comment]
It's solved now! Closing the PR.
