### ISSUE TITLE
Remove the repeating data

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#323]
One need to remove the repeating the data of `/data/contributors.js` as there are some contributor data which is repeated 2 - 3 times.

Like there is 3 **Ishika Ishani** in the list. But it should be only one.

And don't delete any of the contributor data.

**Comment by hfr58gb** [comment]
can you assign me?

**Comment by ProtyayMnd50** [comment]
Can you assign me this? I have committed changes to it for you to review.

**Comment by hfr58gb** [comment]
Task done for required issue, check the [PR](https://github.com/Clueless-Community/first-contribution/pull/327)

**Comment by SattyamSamania** [comment]
Hey @Rajdip019  can I work on this issue if it is still open?

**Comment by Rajdip019** [comment]
You are assigned @hfr58gb

**Comment by Rajdip019** [comment]
This issue is solved so closing the issue
