### ISSUE TITLE
Re-order contributors card

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#334]
We need 4 contributors card on top. They are mixed up now as a lot of people added their data in random places and not at the last.

<img width="1364" alt="Screenshot 2022-10-07 at 11 06 07 AM" src="https://user-images.githubusercontent.com/91758830/194475266-7ebf86db-eca2-4552-9277-2c9f57895556.png">

We need the four card in the top in this order. 
1. Rajdeep Sengupta
2. Roshan Kumar
3. Nikhil Raj
4. Debajyoti Saha

You need to change the `/data/contributors.js` and place the data properly to get the cards also in place.

**Comment by s-vamshi** [comment]
Hey i would like to work on this issue. Can you assign it to me?

**Comment by Rajdip019** [comment]
Yes sure. @s-vamshi

**Comment by s-vamshi** [comment]
@Rajdip019 Thanks for assigning i have made a PR can you please review?

**Comment by Rajdip019** [comment]
Very well done. This issue is resolved so closing this issue @s-vamshi
