### ISSUE TITLE
Pratham Rastogi

### ISSUE THREAD

**Issue by Pratham-R** [Clueless-Community/first-contribution#345]
### This is Pratham Rastogi. And I will be adding my data to do my first contribution as well as get a card on the website.

**Comment by Rajdip019** [comment]
Where is your PR?

**Comment by Pratham-R** [comment]
Sorry i just contributed to contributor.js and not to contributor.md . I am fixing that and opening a Pull Request

**Comment by Rajdip019** [comment]
Okay sure make sure to take the latest pull from main @Pratham-R

**Comment by Pratham-R** [comment]
Sure.

**Comment by Pratham-R** [comment]
PR #350

**Comment by Rajdip019** [comment]
Your PR is merged I guess so closing this issue. @Pratham-R
