### ISSUE TITLE
Add basic git commands page link in footer

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#347]
In the footer section under resources section add another link to this page.

`https://clueless.vercel.app/whattodo/basic-github-commands`.

You should use a Link tag here and the href will be `/whattodo/basic-github-commands"` .

Please add a screenshot after you make a PR.

**Comment by Subhajitongit** [comment]
Hey @Rajdip019 , can you assign this task to me?

**Comment by Rajdip019** [comment]
Sure go ahead

**Comment by Rajdip019** [comment]
Sure go ahead

**Comment by Subhajitongit** [comment]
### Here's the PR for the issue!
[https://github.com/Clueless-Community/first-contribution/pull/360](url)

**Comment by Rajdip019** [comment]
Closing this issue as it is done.
