### ISSUE TITLE
Add new attribute to all the links of Social

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#348]
Add a `target="_blank"` attribute to all the social links in the Footer section. In this way the social links will open in a new tab.

**Comment by YashPimple** [comment]
@Rajdip019 can you assign it to me would like to work on it?

**Comment by myGlitches** [comment]
Can I work on this @Rajdip019 Finished the previous one

**Comment by Rajdip019** [comment]
It's first come first serve. So go ahead and work on it. @YashPimple

**Comment by Rajdip019** [comment]
This issue is solved so closing this issue. @myGlitches
