### ISSUE TITLE
The navbar in the Basic GitHub Commands page color problem

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#352]
The navbar somehow has a different color or looks like a different color. 

Here is a reference to that ⬇️ 

<img width="1440" alt="Screenshot 2022-10-06 at 11 01 19 AM" src="https://user-images.githubusercontent.com/91758830/194222220-a53fbbde-6f89-45be-a83e-df99ad08b88b.png">

Need to fix it so it look consistent.

[Link to the page](https://clueless.vercel.app/whattodo/basic-github-commands)

**Comment by myGlitches** [comment]
Can I work on this then?
Assign it to me @Rajdip019 :D

**Comment by Rajdip019** [comment]
Sure go ahead @myGlitches

**Comment by Ashpreetwadhwa** [comment]
@Rajdip019 
I would love to work on this, 
I can change its colour
Please assign me this task

**Comment by Rajdip019** [comment]
It's already assigned to @myGlitches

**Comment by myGlitches** [comment]
Hey this issue is solved , can you close this @Rajdip019

**Comment by Rajdip019** [comment]
Yeah sure. @myGlitches
