### ISSUE TITLE
Add Bottom To Top Button

### ISSUE THREAD

**Issue by Volley-Freak** [Clueless-Community/first-contribution#356]
### Hii This is Hritik. I think there's should be a bottom to top button with up-arrow icon in your website.
I'll be grateful if you assign this task to me

**Comment by Rajdip019** [comment]
If I am not wrong it's already there. Please check once. @Volley-Freak

**Comment by Volley-Freak** [comment]
Yes you're right. Actually i've seen [This Page](https://clueless.vercel.app/whattodo/basic-github-commands) and assume that it is missing in every page.

**Comment by Rajdip019** [comment]
You can add the Bottom to Top button in this page. Make sure to use the same button used in every page. @Volley-Freak

**Comment by Volley-Freak** [comment]
I've made the changes. Have  a look please.

**Comment by Rajdip019** [comment]
This issue is solved so, closing this Issue. @Volley-Freak
