### ISSUE TITLE
Here can we add link of home page so visitor can redirect to there from this.

### ISSUE THREAD

**Issue by Akshay-21** [Clueless-Community/first-contribution#361]
### This is Akshay. And I will be adding my data to do my first contribution as well as get a card on the website.

![image](https://user-images.githubusercontent.com/32409386/194530774-5d5d1254-3807-4274-a4eb-3e819a3e840c.png)

**Comment by Akshay-21** [comment]
Hey Hi @Rajdip019, can we change like this.
i want to work on that, could you pls assign me this?

**Comment by mehraankush** [comment]
hey i can do that

**Comment by Rajdip019** [comment]
Sure @Akshay-21 go ahead!

**Comment by vaibhav-87** [comment]
Hello! I just came here from your LinkedIn post and found that I can solve this issue. So will you assign it to me?

**Comment by Akshay-21** [comment]
> Sure @Akshay-21 go ahead!

Thank You !

**Comment by Rajdip019** [comment]
This is solved i guess so closing this issue. @Akshay-21
