### ISSUE TITLE
Home pages(HeroDark & HeroLight) content gets hidden behind navbar

### ISSUE THREAD

**Issue by s-vamshi** [Clueless-Community/first-contribution#368]
HeroDark and HeroLight components aren't responsive. Depending on the device we open the website, the content gets hidden.

**It works well in desktop view with 1440 x 483 size.**
![c1](https://user-images.githubusercontent.com/62489114/194547488-270b974d-aeec-4761-b789-ed93f3e8b072.PNG)

**Here is the tablet view and we can see that content is hidden behind navbar.**
![c3](https://user-images.githubusercontent.com/62489114/194547504-bb5a27b7-882e-4378-83b3-dd406a2311c5.PNG)

**Same thing happens in the mobile view as well.**
![c4](https://user-images.githubusercontent.com/62489114/194547502-c50660df-9901-4345-94df-b189bc5b4c00.PNG)

**Comment by s-vamshi** [comment]
@Rajdip019 Can I work on this issue?

**Comment by Rajdip019** [comment]
Sure this is an important issue to solve. Go ahead @s-vamshi

**Comment by Rajdip019** [comment]
This issue is solved I guess so closing this issue. @s-vamshi

**Comment by s-vamshi** [comment]
> This issue is solved I guess so closing this issue. @s-vamshi

Yes, this issue has been solved
