### ISSUE TITLE
Fix two links

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#389]
We now have two Basic GitHub Commands in the Footer. 

<img width="233" alt="Screenshot 2022-10-07 at 8 02 23 PM" src="https://user-images.githubusercontent.com/91758830/194578709-6710f026-575c-44dc-bbec-f4a900f8f4e7.png">

We need the one with the `<Link>` tag and the animation from the `anchor` tag.

**Comment by RidhamRj** [comment]
@Rajdip019 i can work over this

**Comment by FixxooXD** [comment]
@Rajdip019 can you explain it properly, you want to remove BASIC Github "commandsBasic"?

**Comment by RidhamRj** [comment]
> @Rajdip019 can you explain it properly, you want to remove BASIC Github "commandsBasic"?

someone already made a pr resolving this
