### ISSUE TITLE
Add a first contribution instruction page.

### ISSUE THREAD

**Issue by AbirSantra** [Clueless-Community/first-contribution#395]
Hi, I would like to suggest adding a first contribution instruction page when the "Get Your Contributor Card!" button is clicked.

![image](https://user-images.githubusercontent.com/78201921/194586546-0fa4ebe1-cd9b-45f3-acfd-b04fcc92fe28.png)

Currently, the button routes to the GitHub repository page directly. I suggest adding an instructions page on the website itself with the exact instructions as the readme or even improved instructions instead of directly redirecting to Github. I think this would make it more beginner-friendly and easy to access instructions anytime.

I would like to work on this issue under Hacktoberfest. Kindly assign me this issue if approved as a valid issue.

Thank you,
Abir Santra

**Comment by Rajdip019** [comment]
Sure I was also thinking about it. Refer to CONTRIBUTING.md for that. And go ahead build it. @AbirSantra

**Comment by AbirSantra** [comment]
Sure thanks! I'll get started

**Comment by Rajdip019** [comment]
This issue is solved, so closing this issue. @AbirSantra
