### ISSUE TITLE
Bug in footer

### ISSUE THREAD

**Issue by sumitkr2000** [Clueless-Community/first-contribution#407]
Hey @Rajdip019 There is bug in navbar. I want to fix it and also want to align copyright in the center so that it will look better. Please assign me this issue. I have added a screenshot for the reference. Thank you.

![Screenshot (377)](https://user-images.githubusercontent.com/100675296/194618657-8c8dfb5a-288e-4080-92ee-8d73dccf3780.png)

**Comment by JASKIRAT11011** [comment]
hello @sumitkr2000 , can you please assign me this issue

**Comment by HoneyTyagii** [comment]
hey @sumitkr2000  you can assign this issue to me I can work on it.

**Comment by Rajdip019** [comment]
Go ahead @sumitkr2000

**Comment by sumitkr2000** [comment]
@Rajdip019 Why is npm start not working? Can you please tell me the command to preview the webpage?

**Comment by Rajdip019** [comment]
Please follow [setup.md](https://github.com/Clueless-Community/first-contribution/blob/main/SetUp.md) @sumitkr2000

**Comment by sumitkr2000** [comment]
I did it using StackOverflow op!

**Comment by Rajdip019** [comment]
Good keep working 🚀

**Comment by sumitkr2000** [comment]
Bro @Rajdip019 My changes are not reflecting in localhost. I tried clearing out the cache and running the page in incognito mode but nothing is happening. Please give me a solution.

**Comment by Rajdip019** [comment]
This issue is solved I guess. So closing this issue. @sumitkr2000

**Comment by sumitkr2000** [comment]
Yes, its solved now @Rajdip019
