### ISSUE TITLE
Whitespace on Button sides acting like button.

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#409]
It's getting redirected to `github` even when I CLICK anywhere beside the button. Need to fix that.

<img width="1338" alt="Screenshot 2022-10-07 at 11 50 59 PM" src="https://user-images.githubusercontent.com/91758830/194625961-d4902489-d274-47c7-869f-8c4d6bddc649.png">

**Comment by Chaitanya-087** [comment]
i would like to work on this issue

**Comment by Rajdip019** [comment]
Go ahead work on it. @Chaitanya-087

**Comment by jyotika6221** [comment]
Please assign me this issue.
