### ISSUE TITLE
Search as you type

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#410]
We need to implement search as you type in the search bar. There will be no need of the search button.

<img width="1367" alt="Screenshot 2022-10-07 at 11 51 25 PM" src="https://user-images.githubusercontent.com/91758830/194626478-e730dbcf-54df-457e-86b9-037ea1fe25cb.png">

**Comment by saimaheshtaduri** [comment]
I can work on that if you assign it to me. @Rajdip019

**Comment by Rajdip019** [comment]
Yup work on it. @saimaheshtaduri

**Comment by saimaheshtaduri** [comment]
you want me to remove the button and place the search bar on the whole width ?

**Comment by Rajdip019** [comment]
Yes.

**Comment by saimaheshtaduri** [comment]
You assigned me right to this issue ?

**Comment by Rajdip019** [comment]
You work on it. This pr will not be counted @saimaheshtaduri . And are you in our discord server if yes then what is your discord user name?

**Comment by saimaheshtaduri** [comment]
Yes I am on your discord. user name:  vampire »#5783

**Comment by Rajdip019** [comment]
OKay got it.

**Comment by Rajdip019** [comment]
This issue is resolved so closing this issue.
