### ISSUE TITLE
Style input field

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#411]
we need to style the input field for this input field. Try to use the consistent design. And make dark mode and light mode different.

<img width="1280" alt="Screenshot 2022-10-07 at 11 51 17 PM" src="https://user-images.githubusercontent.com/91758830/194626711-e303cbf0-24b0-4706-ac3f-9a7f41f1145e.png">

**Comment by vansh-2266** [comment]
can you assign this to me @Rajdip019 ?

**Comment by Rajdip019** [comment]
Go ahead @vansh-2266

**Comment by jyotika6221** [comment]
Please assign me this issue.

**Comment by Rajdip019** [comment]
This is solved so closing this issue. @vansh-2266
