### ISSUE TITLE
Style the button

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#412]
We need the search button to have a consistent design as the other buttons. We need to implement that.

<img width="137" alt="Screenshot 2022-10-07 at 11 51 09 PM" src="https://user-images.githubusercontent.com/91758830/194627024-d98e7f98-b377-4bce-8e5d-472f1cd7ab2e.png">

**Comment by sunidhisachan** [comment]
@Rajdip019 I want to try this , can you assign this to me?

**Comment by Rajdip019** [comment]
yes sure go ahead ! @sunidhisachan

**Comment by codernirdesh** [comment]
Hi @Rajdip019 I addressed this issue in my PR ( #430 ). Please have a look at it.

**Comment by Swap-nil-2003** [comment]
@Rajdip019 has this issue been resolved? If not then may I look into it?

**Comment by Rajdip019** [comment]
This issue is resolved so closing the issue
