### ISSUE TITLE
change the font style of github commands in commands page

### ISSUE THREAD

**Issue by saimaheshtaduri** [Clueless-Community/first-contribution#421]
Now the github commands aren't readable. It would be better if the desc of the command and the command are distinguished.

**Comment by shawshankkumar** [comment]
Hey @saimaheshtaduri I would like to work on this. Could you please assign this to me and tell me a little more so that I can work on this.

**Comment by Rajdip019** [comment]
Hey @saimaheshtaduri you can work on this.

**Comment by jyotika6221** [comment]
Please assign me this issue.

**Comment by Rajdip019** [comment]
This issue is solved so closing the issue.
