### ISSUE TITLE
Search for Card only searches for lower case letters in Card Name

### ISSUE THREAD

**Issue by s-vamshi** [Clueless-Community/first-contribution#443]
**I am going to search for raj so rajdeep card should be shown-**
![c7](https://user-images.githubusercontent.com/62489114/194696314-2b475289-ebfd-4ddb-a4d8-fff1e4e9bbf3.PNG)

**But this doesn't happen as shown in the below image only two cards are shown -**

![c9](https://user-images.githubusercontent.com/62489114/194696525-77fcd988-fe02-4a52-8f97-7b9dac167f95.PNG)

**Comment by s-vamshi** [comment]
@Rajdip019 I would like to work on this issue, can you assign this to me?

**Comment by Rajdip019** [comment]
Make it case insensitive. @s-vamshi  Work o this.

**Comment by s-vamshi** [comment]
#448 Here is my PR, can you review it?

**Comment by Rajdip019** [comment]
This issue is solved so closing this issue.
