### ISSUE TITLE
Footer Spacing needed under 

### ISSUE THREAD

**Issue by myGlitches** [Clueless-Community/first-contribution#454]
### This is Suryadipta , a little space under the "2022 Clueless" footer text is needed

 
![Footer Spacing](https://user-images.githubusercontent.com/65249625/194701154-f087c630-2b39-4b3b-ab31-b94ce6d69912.png)

**Comment by myGlitches** [comment]
Assign this to me @Rajdip019 will work on it

**Comment by Rajdip019** [comment]
Work on this @myGlitches

**Comment by myGlitches** [comment]
Thanks , on it!

**Comment by myGlitches** [comment]
Hey @Rajdip019 this is done and sent a pull request

**Comment by Rajdip019** [comment]
This issue is solved so closing this issue.
