### ISSUE TITLE
Adding the UI design of error 404 pages.

### ISSUE THREAD

**Issue by Pushkar03** [Clueless-Community/first-contribution#467]
I can contribute by providing a UI design of error 404 pages in both Web and App mode.

**Comment by blyncnov** [comment]
Can i work on this issue ?

**Comment by Rajdip019** [comment]
Sure @Pushkar03 work on this.

**Comment by Pushkar03** [comment]
### **Adding Error 404 Pages UI design in both Dark & Light mode**

**_Dark Mode_**
![404-Space](https://user-images.githubusercontent.com/81770626/194740963-5ecbb2ca-6fc1-4eba-9890-4f791155f15c.png)

_**Light Mode**_
![404-Space(1)](https://user-images.githubusercontent.com/81770626/194740965-0bfc4d49-1c55-4549-ad02-d6bfe8d04541.png)

**Comment by Rajdip019** [comment]
This looks really amazing. Add them @blyncnov

**Comment by Pushkar03** [comment]
Hey I have made them

**Comment by Pushkar03** [comment]
This is my contribution not the other's one

**Comment by blyncnov** [comment]
@Rajdip019 What do you mean add them ?

**Comment by Rajdip019** [comment]
This is solved so closing this isssue.
