### ISSUE TITLE
Layout issue on "/allcontributors" page if there are no search results

### ISSUE THREAD

**Issue by SubxX** [Clueless-Community/first-contribution#468]
Noticed if there are no results in  "/allcontributors" page after searching it creates a lot of empty space ideally footer should stick to the bottom and we can show some kind of message like this
> No search result found with **serch keyword**

I would like to work on this.

![layout issue](https://user-images.githubusercontent.com/51792949/194707575-f00be45b-f3f3-45b6-ad01-2743addfdee5.PNG)

**Comment by blyncnov** [comment]
can I work on this?

**Comment by SubxX** [comment]
thanks for the quick feedback @blyncnov I want to work on this.

**Comment by blyncnov** [comment]
okay

**Comment by Rajdip019** [comment]
Hey @SubxX go ahead and work on this. An svg will be fine. Saying that nothing found.

**Comment by SubxX** [comment]
I have created a [PR](https://github.com/Clueless-Community/first-contribution/pull/479) for this task also I think you forgot to assign me to this task @Rajdip019

**Comment by Rajdip019** [comment]
This issue is solved so closing this issue.
