### ISSUE TITLE
Make your first Contribution

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#48]
Use the First Contribution template and raise an issue and make a PR attached to that.

See the [CONTRIBUTING.md](https://github.com/Clueless-Community/first-contribution/blob/main/CONTRIBUTING.md) for more detailed info on how to contribute.

Still stuck join our discord server and we are always available to help there : [Discord](https://discord.gg/zrVMjGW8sB)

**Comment by RahulSankhla312** [comment]
hey @Rajdip019 can you assign this issue to me ?

**Comment by RahulSankhla312** [comment]
@Rajdip019 I am new to open source .

**Comment by Roshaen** [comment]
@RahulSankhla312 Anyone can contribute to this repo. Go on

**Comment by Rajdip019** [comment]
> hey @Rajdip019 can you assign this issue to me ?

This is not an issue to be assigned. I would suggest you to visit the [CONTRIBUTING.md](https://github.com/Clueless-Community/first-contribution/blob/main/CONTRIBUTING.md)

And see what you need to do. And be careful if you want it to be count in hacktoberfest. You need to make the PULL Request after 1st October.

**Comment by tmsagarofficial** [comment]
OK thanks for the info will definitely make a PR after October 1st.

**Comment by Kumar-Ankit56** [comment]
@Rajdip019  plz assign me I also want to contribute in your repo to get my contribute card

**Comment by tmsagarofficial** [comment]
Pls assign this to me also so that I can complete my first pr from ur repo .😅

**Comment by Rajdip019** [comment]
> @Rajdip019 plz assign me I also want to contribute in your repo to get my contribute card

Hey you don't need to get assigned for this just raise an PR with your data and that will be fine.

**Comment by Rajdip019** [comment]
> Hey you don't need to get assigned for this just raise an PR with your data and that will be fine.

Hey you don't need to get assigned for this just raise an PR with your data and that will be fine.

**Comment by minhaj-313** [comment]
Hi I want to contribute on your Project Could you Please Assign My PR for Hacktoberfest

**Comment by Rajdip019** [comment]
Yeas go ahead and make PR! @minhaj-313

**Comment by minhaj-313** [comment]
> Yeas go ahead and make PR! @minhaj-313

OK Thank. Can Suggest to me Something What Can I do?

**Comment by Rajdip019** [comment]
See other Issues. @minhaj-313

**Comment by minhaj-313** [comment]
> See other Issues. @minhaj-313

I did it Please Merge my PR and please give label as Accepted hactoberfest.
Thank You, and Love to this project

**Comment by guha-rahul** [comment]
Hey @Rajdip019  i updated my details. This will be included in the hacktoberfest right?

**Comment by Rajdip019** [comment]
Yes it will be @guha-rahul
