### ISSUE TITLE
className must be used instead of class for applying classes

### ISSUE THREAD

**Issue by SubxX** [Clueless-Community/first-contribution#487]
This is a refactor-related task. There are a lot of places where `class` is being used instead of `className`. 
I have already made those changes in a branch.
Happy to send a PR anytime.

![image](https://user-images.githubusercontent.com/51792949/194716702-2b5d8859-63ab-4108-a77a-053a5917574d.png)

**Comment by Darainn** [comment]
@SubxX assign this to me

**Comment by SubxX** [comment]
@Darainn sorry man Its already done waiting for confirmation so that I can create a PR.

**Comment by Rajdip019** [comment]
Go ahead do this. @SubxX

**Comment by SubxX** [comment]
[PR](https://github.com/Clueless-Community/first-contribution/pull/521) created @Rajdip019

**Comment by Rajdip019** [comment]
This issue is solved so closing is issue.
