### ISSUE TITLE
Fix the contributor Card Component

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#49]
The card looks broken when we have a big college name. Here is reference of that.
 
<img width="1284" alt="Screenshot 2022-09-29 at 7 23 14 PM" src="https://user-images.githubusercontent.com/91758830/193228835-68aa3943-04c5-408d-a266-dacbfb5977aa.png">

Need to fix that issue ASAP.

**Comment by Dun-sin** [comment]
Hi, can i work on this?

**Comment by Rajdip019** [comment]
Yes sure you can! I will be assigning you for this task tomorrow when hacktoberfest kicks off. 

@Dun-sin

**Comment by Dun-sin** [comment]
> Yes sure you can! I will be assigning you for this task tomorrow when hacktoberfest kicks off.
> 
> @Dun-sin

no problem

**Comment by Dun-sin** [comment]
thanks

**Comment by mushtaq96** [comment]
Hi can I contribute to this, if the other person is unavailable due to any issues?

**Comment by Rajdip019** [comment]
Yes sure! if he is unable to do this you will be assigned next. @mushtaq96

**Comment by Rajdip019** [comment]
This issue is resolved so closing this.

**Comment by Dun-sin** [comment]
> This issue is resolved so closing this.

Seriously? Wow okay
