### ISSUE TITLE
Add Video for more Info about what is Git and GitHub

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#50]
In the whattodo page of ([clueless.vercel.app](https://clueless.vercel.app/whattodo)) website wen need to add a section at the end, where (this video)[https://www.youtube.com/watch?v=apGV9Kg7ics&t=3s].

And the video should be playable from the website itself.

**Comment by Noothan-am** [comment]
hey, @Rajdip019 I wanted to contribute to this repo so should I add a video section above footer?

**Comment by Rajdip019** [comment]
> hey, @Rajdip019 I wanted to contribute to this repo so should I add a video section above footer?

Go ahead. I will be assigning you to this issue after the Hacktoberfest kicks off tomorrow.

**Comment by tmsagarofficial** [comment]
Pls let me know if I can also work on this .

**Comment by Noothan-am** [comment]
yes

**Comment by Noothan-am** [comment]
@Rajdip019 yes i am working on it

**Comment by Rajdip019** [comment]
Okay..

**Comment by Noothan-am** [comment]
hey, @Rajdip019   I need to clear some dought about this could you help me?

**Comment by Rajdip019** [comment]
Yes sure. head-over to [Discord](https://discord.gg/zrVMjGW8sB) and ask your doubt.

**Comment by tmsagarofficial** [comment]
Is this issue still open ??

Can i also contribute?

**Comment by Rajdip019** [comment]
Yes, it's open but @Noothan-am is working on it. If he fails to do this you can surely work on this. Till the you can find bugs and new things we can add in this [website](https://clueless.vercel.app/).

And raise your own issue and work on that. @tmsagarofficial

**Comment by Noothan-am** [comment]
sorry @Rajdip019 you can assign it to someone else I am new to open source so I am not getting exactly how to do it

**Comment by AKACHI-4** [comment]
Hey @Rajdip019  I am able to solve this issue Kindly assign it to me so I can make expected changes

**Comment by Rajdip019** [comment]
Hey @AKACHI-4 @itsmeAnubhab has already done it and made the PR so merging his PR.

**Comment by Rajdip019** [comment]
This issue is closed as it is solved.
