### ISSUE TITLE
Fix text in website

### ISSUE THREAD

**Issue by Rajdip019** [Clueless-Community/first-contribution#51]
### This should be contribute instead of donate.

<img width="1066" alt="Screenshot 2022-09-30 at 2 11 59 PM" src="https://user-images.githubusercontent.com/91758830/193230343-9712a11e-db5d-4f0b-9f3b-cb14ad2780a6.png">

**Comment by RahulSankhla312** [comment]
hey @Rajdip019  i would like to contribute to this issue .

**Comment by Rajdip019** [comment]
> hey @Rajdip019  i would like to contribute to this issue .
> 

Sure. I will be assigning you after the hacktoberfest kicks off.

**Comment by Hussain6** [comment]
hey @Rajdip019 can you assign this to me so I can contribute to this repo.

**Comment by Rajdip019** [comment]
This issue is solved so closing this.
