### ISSUE TITLE
contributors cards redirect to respective profiles

### ISSUE THREAD

**Issue by saimaheshtaduri** [Clueless-Community/first-contribution#534]
On clicking on the contributor card, I feel its better if its redirected to their profile page.

**Comment by Rajdip019** [comment]
Yes I also feel the same. Their profile should open in a new tab. And it should be their github profile. @saimaheshtaduri You can work on that.

**Comment by Rajdip019** [comment]
This issue is solved so closing this. @saimaheshtaduri
