### ISSUE TITLE
This repo isnt accepted for hacktoberfest

### ISSUE THREAD

**Issue by Ahnaf-codes** [Clueless-Community/first-contribution#539]
I fixed an issue but as you can see it was ***Excluded*** since this repo **doesnt follow the values of hacktoberfest**
![Screenshot 2022-10-10 at 14-32-53 Profile Hacktoberfest 2022](https://user-images.githubusercontent.com/102795582/194826431-a7f7ccfc-529e-4fc7-b636-52fa154ccb43.png)

![Screenshot 2022-10-10 at 14-32-16 Profile Hacktoberfest 2022](https://user-images.githubusercontent.com/102795582/194826437-8a8dcbf8-17b7-4c22-b176-0f3282154866.png)

**Comment by Rajdip019** [comment]
We are extremely sorry to inform you that this repo is excluded from Hactoberfest 2022 😢

But the contribution you made will not go waste, it still counts in for swags by Clueless.

We are also trying to fix this issue getting in touch with hacktoberfest.
