### ISSUE TITLE
Error: while searching for contributor's details by name 

### ISSUE THREAD

**Issue by Alkaison** [Clueless-Community/first-contribution#620]
![image](https://user-images.githubusercontent.com/98116504/217777033-e5d63099-8140-4a78-96a2-aee6487bbdd3.png)
<br>
![image](https://user-images.githubusercontent.com/98116504/217777125-2fa5ade9-b4cf-45f9-9fe5-edc42d8cfee5.png)

Page link: https://clueless.vercel.app/allcontributors

**Comment by nikhil25803** [comment]
@Alkaison, go ahead. Make a try to fix it.

**Comment by Alkaison** [comment]
#621

**Comment by Alkaison** [comment]
- The PR fixes the search user details issue. #621
